export class Company {
  ID: number = 0;
  CompanyName: string = '';
  MobileNo1: string = '';
  MobileNo2: string = '';
  PhoneNo: string = '';
  Address: string = '';
  Country : string = '';
  State : string = '';
  City : string = '';
  Email: string = '';
  Website: string = '';
  GSTNo: string = '';
  CINNo: string = '';
  LogoURL: string = '';
  Remark: string = '';
  Plan: string = '';
  Version: string = '';
  NoOfShops: string = '';
  EffectiveDate: Date = new Date() ;
  CancellationDate: Date =  new Date() ;
  WhatsappMsg : Boolean = false;
  EmailMsg : Boolean = false;;
  WholeSale :Boolean = false;;
  RetailPrice :Boolean = false;;
  Status: number = 0;
  CreatedBy: number =0;
  CreatedOn: any;
  UpdatedBy: number=0;
  UpdatedOn: any;
  dataFormat: any;
  SRemark:any;
  CAmount:any;
}
